Vagrant.configure("2") do |config|
   config.vm.box = "debian/jessie64"

   config.vm.network "private_network", ip: "127.0.0.1"
   config.vm.network "forwarded_port", guest: 80, host: 8080

   config.vm.provider "virtualbox" do |vb|
    vb.name = "compagnonVM"
   end

   config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/playbook.yml"
    ansible.limit = "all"
   end
end

